<?php
/**
 * Embedded iframe with Langshop application
 *
 * @var \Magento\Backend\Block\Template $block
 * @var \Aheadworks\Langshop\ViewModel\Page\Iframe $viewModel
 */
$viewModel = $block->getViewModel();
?>
<iframe src="<?= $block->escapeUrl($viewModel->getSourceUrl()) ?>"
        width="100%"
        height="1000px"
        frameborder="0"
        sandbox="allow-same-origin allow-scripts"
        data-mage-init='{"Aheadworks_Langshop/js/iframe-bridge": {}}'
></iframe>
