<?php
/**
 * @var $block \Magento\Backend\Block\Template
 * @var $viewModel \Aheadworks\Langshop\ViewModel\Page\Iframe
 */
$viewModel = $block->getViewModel();
?>
<iframe src="<?= /* @noEscape */ $viewModel->getSourceUrl() ?>"
        frameborder="0" width="100%" height="1000px"
        sandbox="allow-same-origin allow-scripts"
        data-mage-init='{"Aheadworks_Langshop/js/iframe-bridge": {}}'></iframe>
